# Copyright Commonwealth of Australia, Bureau of Meteorology 2024.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""
Met Office specific Indexes

| Name        | Description |
| :---        |       ----: |
| [ERA5][site_archive_jasmin.ERA5lowres]   | ECWMF ReAnalysis v5 WeatherBench Low Res       |
| [MOGLOBAL][site_archive_jasmin.MOGLOBAL] | Subset of Met Office Global Analysis Data      |
| [MOUKV][site_archive_jasmin.MOUKV]       | Subset of Met Office UKV Analysis Data         |
"""

import os
from pyearthtools.data.archive import (
    register_archive,
    load_root_directories_from_config,
)


ROOT_DIRECTORIES = {
    "ERA5lowres": "",
    "MOGLOBAL": "",
    "MOUKV": "",
}

register_archive("ROOT_DIRECTORIES")(ROOT_DIRECTORIES)

import site_archive_jasmin  # noqa

from site_archive_jasmin.ERA5lowres import ERA5lowres  # noqa
from site_archive_jasmin.MOGLOBAL import MOGLOBAL  # noqa
from site_archive_jasmin.MOUKV import MOUKV  # noqa

register_archive("jasmin")(site_archive_jasmin)

# Load the Met Office PyEarthTools config file to set the root directories
config_path = os.path.expanduser("~/.pyearthtoolsconfig")
load_root_directories_from_config(config_path=config_path)

try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__  # type: ignore
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"


__all__ = ["MOUKV", "MOGLOBAL", "ERA5lowres"]
