# (C) British Crown Copyright 2017-2025, Met Office.
# Please see LICENSE.md for license details.

"""
Met Office specific Indexes

| Name        | Description |
| :---        |       ----: |
| [ERA5][site_archive_jasmin.ERA5lowres]   | ECWMF ReAnalysis v5 WeatherBench Low Res       |
| [MOGLOBAL][site_archive_jasmin.MOGLOBAL] | Subset of Met Office Global Analysis Data      |
| [MOUKV][site_archive_jasmin.MOUKV]       | Subset of Met Office UKV Analysis Data         |
| [BARRA_V2][site_archive_nci.BARRA_V2]        | Bureau of meteorology Atmospheric high-resolution Regional Reanalysis for Australia v2 |
| [Himawari][site_archive_nci.Himawari]        | Himawari 8/9 satellite data                             |
| [Rainfields3][site_archive_nci._Rainfields3] | Rainfields3 Australia-wide radar mosiac 2km^2 (Ausm310) |


"""

import os
from pyearthtools.data.archive import (
    register_archive,
    load_root_directories_from_config,
)


ROOT_DIRECTORIES = {
    "ERA5lowres": "",
    "MOGLOBAL": "",
    "MOUKV": "",
}

register_archive("ROOT_DIRECTORIES")(ROOT_DIRECTORIES)

import site_archive_jasmin  # noqa

from site_archive_jasmin.ERA5lowres import ERA5lowres  # noqa
from site_archive_jasmin.MOGLOBAL import MOGLOBAL  # noqa
from site_archive_jasmin.MOUKV import MOUKV  # noqa
from site_archive_jasmin.Himawari import MOUKV  # noqa
from site_archive_jasmin.MOUKV import MOUKV  # noqa
from site_archive_jasmin.MOUKV import MOUKV  # noqa

register_archive("jasmin")(site_archive_jasmin)

# Load the Met Office PyEarthTools config file to set the root directories
config_path = os.path.expanduser("~/.pyearthtoolsconfig")
load_root_directories_from_config(config_path=config_path)

try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__  # type: ignore
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"


__all__ = ["MOUKV", "MOGLOBAL", "ERA5lowres"]
