# Copyright Commonwealth of Australia, Bureau of Meteorology 2024.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


ERA5_PRESSURE_VARIABLES = [
    "t",
    "u",
    "v",
]

ERA5_SINGLE_VARIABLES = [
    "u10",
    "10u",
    "v10",
    "10v",
    "2t",
    "tcc",
]

# ERA5_PRESSURE_VARIABLES = [
#     "d",
#     "cc",
#     "z",
#     "o3",
#     "pv",
#     "r",
#     "ciwc",
#     "clwc",
#     "q",
#     "crwc",
#     "cswc",
#     "t",
#     "u",
#     "v",
#     "w",
#     "vo",
# ]

# ERA5_SINGLE_VARIABLES = [
#     "u100",
#     "v100",
#     "dwi",
#     "u10",
#     "10u",
#     "wind",
#     "v10",
#     "10v",
#     "fg10",
#     "d2m",
#     "2t",
#     "anor",
#     "isor",
#     "bfi",
#     "bld",
#     "blh",
#     "chnk",
#     "cdir",
#     "cbh",
#     "cdww",
#     "cape",
#     "ci",
#     "cin",
#     "cp",
#     "crr",
#     "csf",
#     "csfr",
#     "uvb",
#     "dctb",
#     "lgws",
#     "ewss",
#     "e",
#     "fal",
#     "flsr",
#     "fsr",
#     "p140208",
#     "zust",
#     "gwd",
#     "z_surface",
#     "hcc",
#     "cvh",
#     "istl1",
#     "istl2",
#     "istl3",
#     "istl4",
#     "i10fg",
#     "iews",
#     "ilspf",
#     "ie",
#     "inss",
#     "ishf",
#     "kx",
#     "lblt",
#     "cl",
#     "lict",
#     "licd",
#     "lmld",
#     "lmlt",
#     "lshf",
#     "dl",
#     "ltlt",
#     "lsm",
#     "lsp",
#     "lspf",
#     "lsf",
#     "lsrr",
#     "lssfr",
#     "lai_hv",
#     "lai_lv",
#     "lcc",
#     "cvl",
#     "hmax",
#     "mx2t",
#     "mxtpr",
#     "mbld",
#     "mcpr",
#     "mcsr",
#     "mdts",
#     "mdww",
#     "megwss",
#     "metss",
#     "mer",
#     "mgwd",
#     "mlspf",
#     "mlspr",
#     "mlssr",
#     "mngwss",
#     "mntss",
#     "mpts",
#     "mpww",
#     "mper",
#     "mror",
#     "msl",
#     "mser",
#     "msr",
#     "msmr",
#     "msqs",
#     "mssror",
#     "msdrswrf",
#     "msdrswrfcs",
#     "msdwlwrf",
#     "msdwlwrfcs",
#     "msdwswrf",
#     "msdwswrfcs",
#     "msdwuvrf",
#     "mslhf",
#     "msnlwrf",
#     "msnlwrfcs",
#     "msnswrf",
#     "msnswrfcs",
#     "msror",
#     "msshf",
#     "mtdwswrf",
#     "mtnlwrf",
#     "mtnlwrfcs",
#     "mtnswrf",
#     "mtnswrfcs",
#     "mtpr",
#     "dndza",
#     "mvimd",
#     "mwd",
#     "mwp",
#     "mp1",
#     "p1ps",
#     "p1ww",
#     "p2ps",
#     "p2ww",
#     "mp2",
#     "mcc",
#     "mn2t",
#     "mntpr",
#     "dndzn",
#     "wmb",
#     "alnid",
#     "alnip",
#     "u10n",
#     "v10n",
#     "phioc",
#     "phiaw",
#     "tauoc",
#     "mgws",
#     "nsss",
#     "pp1d",
#     "tmax",
#     "pev",
#     "ptype",
#     "ro",
#     "siconc",
#     "sst",
#     "swh",
#     "shts",
#     "shww",
#     "src",
#     "skt",
#     "slor",
#     "asn",
#     "rsn",
#     "sd",
#     "es",
#     "sf",
#     "smlt",
#     "stl1",
#     "stl2",
#     "stl3",
#     "stl4",
#     "slt",
#     "sdfor",
#     "sdor",
#     "ssro",
#     "slhf",
#     "strd",
#     "str",
#     "strc",
#     "ssr",
#     "ssrc",
#     "sp",
#     "sro",
#     "sshf",
#     "ssrd",
#     "ssrdc",
#     "strdc",
#     "tsn",
#     "tisr",
#     "ttr",
#     "tsr",
#     "tsrc",
#     "ttrc",
#     "tcc",
#     "tciw",
#     "tclw",
#     "tco3",
#     "tcrw",
#     "tcsw",
#     "tcslw",
#     "tcwv",
#     "tcw",
#     "tp",
#     "fdir",
#     "totalx",
#     "tplb",
#     "tplt",
#     "tvh",
#     "tvl",
#     "ust",
#     "aluvd",
#     "aluvp",
#     "vst",
#     "vimd",
#     "swvl1",
#     "swvl2",
#     "swvl3",
#     "swvl4",
#     "wdw",
#     "dwps",
#     "dwww",
#     "wsk",
#     "wsp",
#     "wss",
#     "deg0l",
# ]
